//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grd_grado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grd_grado()
        {
            this.mxg_materiasxgrado = new HashSet<mxg_materiasxgrado>();
        }
    
        public int grd_id { get; set; }
        public string grd_nombre { get; set; }
        public Nullable<System.DateTime> grd_created_at { get; set; }
        public Nullable<System.DateTime> grd_updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mxg_materiasxgrado> mxg_materiasxgrado { get; set; }
    }
}
