//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataBase : DbContext
    {
        public DataBase()
            : base("name=DataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alm_alumno> alm_alumno { get; set; }
        public virtual DbSet<grd_grado> grd_grado { get; set; }
        public virtual DbSet<mat_materia> mat_materia { get; set; }
        public virtual DbSet<mxg_materiasxgrado> mxg_materiasxgrado { get; set; }
    
        public virtual ObjectResult<sp_list_alm_Result> sp_list_alm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_list_alm_Result>("sp_list_alm");
        }
    
        public virtual ObjectResult<sp_list_grado_Result> sp_list_grado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_list_grado_Result>("sp_list_grado");
        }
    
        public virtual ObjectResult<sp_list_mat_Result> sp_list_mat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_list_mat_Result>("sp_list_mat");
        }
    
        public virtual ObjectResult<sp_list_mxg_Result> sp_list_mxg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_list_mxg_Result>("sp_list_mxg");
        }
    
        public virtual int sp_delete_alm(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_alm", idParameter);
        }
    
        public virtual int sp_eliminar_grd(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_grd", idParameter);
        }
    
        public virtual int sp_eliminar_mat(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_mat", idParameter);
        }
    }
}
